<?php
/**
 * AtroCore Software
 *
 * This source file is available under GNU General Public License version 3 (GPLv3).
 * Full copyright and license information is available in LICENSE.txt, located in the root directory.
 *
 * @copyright  Copyright (c) AtroCore GmbH (https://www.atrocore.com)
 * @license    GPLv3 (https://www.gnu.org/licenses/)
 */

namespace Atro\Services;

use Atro\Core\Templates\Services\Archive;
use Espo\ORM\EntityCollection;

class ActionExecutionLog extends Archive
{
    protected $mandatorySelectAttributeList = ['entityName', 'entityId'];

//    public function prepareCollectionForOutput(EntityCollection $collection, array $selectParams = []): void
//    {
//        echo '<pre>';
//        print_r($collection->toArray());
//        die();
//
//        parent::prepareCollectionForOutput($collection, $selectParams); // TODO: Change the autogenerated stub
//
//    }
}
